app:
  name: 智能设备产测工具
  version: '2.8'
device:
  heartbeat_interval: 30
  product_id: '1696'
  psk: weidian_24h
  timeout: 10
mdns:
  service_type: _mqtt._tcp.local.
  timeout: 5
mqtt:
  allow_anonymous: true
  broker: 22.0.0.1
  broker_mode: local
  keepalive: 60
  port: 1881
  qos: 1
  require_certificate: false
  use_identity_as_username: false
printer:
  dpi: 600
  enabled: true
  paper_height: 30
  paper_width: 50
  printer_name: Xprinter XP-T271U
  protocol: auto
  tspl_layout:
    border:
      thickness: 2
      x1: 2
      x2: 398
      y1: 2
      y2: 238
    date:
      font: '1'
      rotation: 0
      x: 120
      x_scale: 1
      y: 124
      y_scale: 1
    qrcode:
      cell_width: 6
      x: 245
      y: 69
    sn:
      font: '1'
      rotation: 0
      x: 34
      x_scale: 1
      y: 178
      y_scale: 1
  zpl_layout:
    date:
      font_height: 80
      font_width: 80
      x: 354
      y: 366
    qrcode:
      magnification: 15
      x: 723
      y: 204
    sn:
      font_height: 80
      font_width: 80
      x: 100
      y: 605
test:
  ble_rssi_threshold: -70
  discover_duration: 5000
  ir_strict_verify: true
  open_duration: 5000
  retry_count: 3
  sle_min_count: 1
  test_timeout: 30
  verify_state: true
  wifi_rssi_threshold: -40
ui:
  layout_mode: 4
  remember_layout: false
  speaker_type: outdoor
